%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-fastdds
Version:        3.2.1
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS fastdds package

License:        Apache 2.0
URL:            https://www.eprosima.com/
Source0:        %{name}-%{version}.tar.gz

Requires:       openssl-devel
Requires:       python%{python3_pkgversion}-devel
Requires:       ros-kilted-fastcdr
Requires:       ros-kilted-foonathan-memory-vendor
Requires:       tinyxml2-devel
Requires:       ros-kilted-ros-workspace
BuildRequires:  asio-devel
BuildRequires:  cmake3
BuildRequires:  openssl-devel
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-fastcdr
BuildRequires:  ros-kilted-foonathan-memory-vendor
BuildRequires:  tinyxml2-devel
BuildRequires:  ros-kilted-ros-workspace
Obsoletes:      ros-kilted-fastrtps
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
eProsima Fast DDS is a C++ implementation of the DDS (Data Distribution Service)
standard of the OMG (Object Management Group). eProsima Fast DDS implements the
RTPS (Real Time Publish Subscribe) protocol, which provides publisher-subscriber
communications over unreliable transports such as UDP, as defined and maintained
by the Object Management Group (OMG) consortium. RTPS is also the wire
interoperability protocol defined for the Data Distribution Service (DDS)
standard. eProsima Fast DDS expose an API to access directly the RTPS protocol,
giving the user full access to the protocol internals.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license LICENSE
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Raul Sanchez Mateos <raulsanchezmateos@eprosima.com> - 3.2.1-2
- Autogenerated by Bloom

* Mon Apr 07 2025 Raul Sanchez Mateos <raulsanchezmateos@eprosima.com> - 3.2.1-1
- Autogenerated by Bloom

* Tue Apr 01 2025 Raul Sanchez Mateos <raulsanchezmateos@eprosima.com> - 3.2.0-1
- Autogenerated by Bloom

* Mon Mar 03 2025 Miguel Company <miguelcompany@eprosima.com> - 3.1.2-2
- Autogenerated by Bloom

* Wed Feb 26 2025 Miguel Company <miguelcompany@eprosima.com> - 3.1.2-1
- Autogenerated by Bloom

